# Generated by Django 5.1.1 on 2024-09-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', to='useraccount.user'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to='useraccount.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='sent_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='useraccount.user'),
            preserve_default=False,
        ),
    ]
