# Generated by Django 5.1.1 on 2024-09-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_alter_reservation_created_by'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='useraccount.user'),
        ),
    ]
