# Generated by Django 5.1.1 on 2024-09-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='uploads/properties'),
        ),
    ]
