# Generated by Django 5.1.1 on 2024-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_advertised',
            field=models.BooleanField(default=False),
        ),
    ]
