# Generated by Django 5.1.1 on 2024-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_is_advertised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_advertised',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
