# Generated by Django 5.1.1 on 2024-10-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_is_advertised'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
