# Generated by Django 5.1.1 on 2024-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_payment_status_property_paymob_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_advertised',
            field=models.BooleanField(default=False),
        ),
    ]
