# Generated by Django 5.1.1 on 2024-09-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_address'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(default='fe215053-e33c-479c-92f6-3b796bb45dab', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='useraccount.user'),
            preserve_default=False,
        ),
    ]
