# Generated by Django 5.1.1 on 2024-10-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_image_propertyimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='advertised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
